---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes

- hosts: webservers
  become: true
  tasks:

  - name: install apache and php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
  - name: copy files
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: shotgun
      group: root
      mode: 0644

- hosts: dbservers
  become: true
  tasks:

  - name: install mariadb
    apt:
      name:
        - mariadb-server
      state: latest

- hosts: fileservers
  become: true
  tasks:

  - name: install samba package
    package:
      name:
        - samba
        - unzip
      state: latest
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: shotgun
      group: root	
